### PR TITLE
Allow overriding internal data array type

### PR DESCRIPTION
**Pull request by tyrasd**
Similar to https://github.com/mourner/kdbush#api – if input coordinates are integer values, using an `Int32Array` could make things a bit faster?

### CODE REVIEW

**Comment by tyrasd** [comment]
crude benchmark (1 million rectangles with integer coordinates):

1.1.2:
```
flatbush: 283.530ms
1000 searches 10%: 1156.619ms
1000 searches 1%: 198.933ms
1000 searches 0.01%: 49.472ms
```

this branch with `flatbush(N, 16, Int32Array)`
```
flatbush: 276.901ms
1000 searches 10%: 804.920ms
1000 searches 1%: 128.280ms
1000 searches 0.01%: 32.238ms
```

**Comment by mourner** [comment]
Great point, thank you!

**Comment by mourner** [comment]
Note that I got the same speed up for Float64Array case with this commit: https://github.com/mourner/flatbush/commit/5edf164ba2416d1e209cceac6a64d479365575f8

Now I'm wondering if it would be better to change the API to accept `isInteger` boolean rather than the type for simplicity (and to avoid people shooting themselves in the foot when using types that won't hold the indices properly, e.g. `Uint8Array`).

**Comment by tyrasd** [comment]
> Note that I got the same speed up for Float64Array case with this commit

Nice, but I do still see up to 25% speed-ups when using a Uint32Array instead of the default.
Btw, using smaller typed arrays can also be beneficial for faster transferring of serialized flatbush-data over the network.

> avoid people shooting themselves in the foot when using types that won't hold the indices properly

I see two options:
* Check at the beginning and throw an exception if the given type can hold the data (something like this should do the trick: `ArrayType.of(numNodes * 5)[0] === numNodes * 5`)
* Refactor the library so that it can handle independent array types for "coordinates" and indices – the index array type could then be automatically chosen to just fit the respective `numNodes`. This could be stored as an array buffer of size ~`numNodes * (ArrayType.BYTES_PER_ELEMENT + IndexArrayType.BYTES_PER_ELEMENT)` where the box data occupies the first part and the indices the latter part of the buffer.

I've actually played around a bit with the second option, and it looks promising: it is slightly faster for the "default" case (Float64Array coordinates with Uint32Array indices, which is in current master represented by a pure Float64Array), and slightly slower when using Uint32Array for everything (probably because of less efficient caching), while still allowing for further speed-ups for example when coordinates or indices can fit into 16 or even 8 bit integers.

What do you think?

**Comment by mourner** [comment]
@tyrasd nice! The first option is certainly the easiest and least intrusive. The second one seems like it would make the code harder to read and debug. Maybe we should consider simply using two arrays instead of one for the index (one will hold the indices and the other one bbox values).

**Comment by tyrasd** [comment]
See #11 for the my above mentioned implementation of "option 2".

**Pull request merged**
