### PR TITLE
Add a header to make it easier to reconstruct the index

### LINKED ISSUE #12: Contain numItems, nodeSize and possibly array type in data buffer?
Currently, transferring and recreating the index is a bit cumbersome because of the need to also transfer other parameters associated with the index:

```js
self.postMessage({
  numItems: index.numItems,
  nodeSize: index.nodeSize,
  data: index.data
}, [index.data]);
...
const index = new FlatBush(e.data.numItems, e.data.nodeSize, Int32Array, e.data.data);
```

What if we include `numItems` and `nodeSize` to the data buffer so they don't need to be transferred? We can also go further and include a numeric indicator of the typed array, so that we only need an array buffer and nothing else to recreate the full index:

```js
self.postMessage(index.data, [index.data]);
...
const index = FlatBush.from(e.data);
```

The number of items and nodeSize will have to be `Uint32Array` because we can't guess the index type from the buffer alone. We would probably put them at the start of `data`. The type would be a number from 0 to 8.

@tyrasd what do you think, worth it?

### PR DESCRIPTION
**Pull request by mourner**
Closes #12. Allows you to do `const index = Flatbush.from(data)` by encoding the number of items, the node size and the array type into the buffer (as an 8-byte header).

### CODE REVIEW

**Comment by tyrasd** [comment]
Great idea.

What about also adding a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) at the start of the buffer, so that it can be checked if the data is actually valid flatbush data? This could for example also help prevent/debug issues of this kind: the data format is changed a bit in the future, but people still try to load in data generated by an older flatbush version (think: backend code not updated to the same flatbush version as the frontend)?

**Comment by tyrasd** [comment]
Also: did you keep the optional constructor parameter `data` on purpose (for backwards compatibility)? I mean, it could be a bit confusing if there are two ways to construct a flatbush object from the same data array buffer…

**Comment by mourner** [comment]
> Also: did you keep the optional constructor parameter data on purpose (for backwards compatibility)? I mean, it could be a bit confusing if there are two ways to construct a flatbush object from the same data array buffer…

No, I kept it because I couldn't come up with a more elegant way to construct a `Flatbush` instance without triggering the "create from scratch" code path. We would not expose it in the docs. An alternative would be to accept a form `new Flatbush(data)`, but I try to avoid polymorphic functions like this in JS and do stuff like `if (numItems instanceof ArrayBuffer) data = numItems`.

**Comment by mourner** [comment]
For the header, alternatively we could fit it in 8 bytes by removing the magic number and keeping just the version:

```
2 bytes: version, typeIndex
2 bytes: nodeSize (<= 65535)
4 bytes: numItems
```

**Comment by mourner** [comment]
@tyrasd added the last proposal (with 1-byte magic number) — let me know what you think.

**Comment by mourner** [comment]
Good point, added!

**Pull request merged**
